name: Run Email Script Daily

on:
  schedule:
    - cron: "0 10 * * *"  # Runs every day at 10:00 UTC
  workflow_dispatch:       # Allows manual triggering from the GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pandas

      - name: Run Python Script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python "CTT Metrics Deploy My Email Method_GitHub(20 March, 2025).py"
