name: Run Daily CTT Metrics Report

on:
  schedule:
    - cron: "0 10 * * *"  # Runs every day at 10:00 UTC
  workflow_dispatch:       # Allows manual triggering from the GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy psycopg2-binary yagmail xlsxwriter pytz

      - name: Run Python Script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python "CTT Metrics Deploy My Email Method_GitHub(20 March, 2025).py"
